### ISSUE TITLE
Example of how to open a file for reading

### ISSUE THREAD

**Issue by cwurld** [jdunck/python-unicodecsv#24]
Hi,

Thanks for writing this. 

I might be useful in your docs to show how to open a file for reading. I was opening the file using:

fp = codecs.open(csv_path, encoding='utf-8'

Evidently that's the wrong thing to do. When I opened it the normal way:

fp = open(csv_path, 'r') 

everything worked.

Thanks,
Chuck

**Comment by jdunck** [comment]
Sorry for leaving this issue unaddressed for so long - both suggestions for doc improvements are good, and I'll do it. :)

**Comment by jdunck** [comment]
Fixed in 39a26b2f0b8b734
