### ISSUE TITLE
DictReader chokes on Python3

### ISSUE THREAD

**Issue by blagarde** [jdunck/python-unicodecsv#25]
Hi there,

I installed 0.10.1 with:
```
$ pip install https://github.com/jdunck/python-unicodecsv/zipball/master#egg=unicodecsv-0.10.1
```

This code instantiating DictReader works fine on 2.7.5 but produces an error on Python >= 3:
```
from __future__ import print_function
from __future__ import unicode_literals
import unicodecsv
from unicodecsv import DictReader
import sys
print(sys.version)
try:
    import StringIO as io
except ImportError:
    pass  # Python >= 3
from io import StringIO
d = DictReader(StringIO('a,b,c\n1,2,3'))
print('yay')
```

Here is the output:
```
$ python test.py 
3.3.3 (default, Jan 14 2014, 20:39:06) 
[GCC 4.6.3]
Traceback (most recent call last):
  File "test.py", line 13, in <module>
    d = DictReader(StringIO('a,b,c\n1,2,3'))
  File "~/.pyenv/versions/3.3.3/lib/python3.3/site-packages/unicodecsv-0.10.1-py3.3.egg/unicodecsv/__init__.py", line 187, in __init__
  File "~/.pyenv/versions/3.3.3/lib/python3.3/csv.py", line 96, in fieldnames
    self._fieldnames = next(self.reader)
TypeError: 'UnicodeReader' object is not an iterator
```

Is anyone able to reproduce this?

**Comment by tsroten** [comment]
@blagarde I don't believe `unicodecsv` is supposed to work on Python 3 as Python 3's `csv` module handles unicode properly. If you need to support Python 2 and 3, try this:
```python
import sys

is_python2 = sys.version_info[0] == 2

if is_python2:
    import unicodecsv as csv
else:
    import csv
```
Then, simply use the `csv` module. In Python 2, it will really use ``unicodecsv``.

**Comment by blagarde** [comment]
Hi @jdunck,
That's what I ended up doing in the PR I submitted last year:
https://github.com/jdunck/python-unicodecsv/pull/26

Are there any strong arguments not to include these lines inside unicodecsv?
Including them would save everyone from having to do it in their own code.

**Comment by DenisCarriere** [comment]
I'm having the same issue with Python3, I usually build my code to support both Python2/3 and I use unicodecsv saving my data in Python2, but when I switch to Python3 I would like for my code not to break.

Great job on all this development, I use this a lot!

**Comment by jdunck** [comment]
I've added py3 in 0.12.0 - please try it out and open another issue if you find specific problems. :)
