### ISSUE TITLE
Retain the order of coulumns in Dictreader

### ISSUE THREAD

**Issue by endeepak** [jdunck/python-unicodecsv#39]
The `csv.DictReader` retains the retain order of columns. The `unicodecsv.DictReader` doesn't.

**Comment by jdunck** [comment]
I merged master into this branch, resolved some conflicts, and bumped the version number into 883555b60160b2.  0.14.0 is now on master and on pypi.

I'm closing the related PR here.

**Comment by jdunck** [comment]
@endeepak Thanks for the issue and code, and sorry it took so long to get merged.

**Comment by ryanhiebert** [comment]
@jdunck: The builtin `csv.DictReader`, in either Python 2 or Python 3, _does not_ retain the order of the columns specified manually.

The new test of this feature breaks for my work in #58, because I'm just extending the built-in `csv` module. I would need to copy-and-paste re-implement the `__next__` method and add this feature to the csv module, and I'd really prefer to not, I see it as unnecessary complication and coupling.

Would you consider reverting this, given that it breaks my Pull Request and is not consistent with the builtin `csv` modules?

----------

```
🐟  python2.7
Python 2.7.10 (default, Aug 26 2015, 18:17:29)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import csv
>>> reader = csv.DictReader(["1,2,3,4"], fieldnames="foo bar baz qux".split())
>>> list(next(reader).keys())
['baz', 'foo', 'bar', 'qux']
>>> exit()
🐟  python3.5
Python 3.5.0 (default, Sep 14 2015, 09:14:42)
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import csv
>>> reader = csv.DictReader(["1,2,3,4"], fieldnames="foo bar baz qux".split())
>>> list(next(reader).keys())
['bar', 'baz', 'qux', 'foo']
>>> exit()
```

**Comment by endeepak** [comment]
@jdunck :  Looks like @ryanhiebert is right about 2 or 3 not retaining the order. I don't remember which version of python I tested previously, But now I get same result as @ryanhiebert when I test with 2.7.10 and 3.4.3. When I raised this PR, I might have tested with some data where I probably got dict keys being in order by random luck.

I guess reverting my commit would be ideal. @ryanhiebert and @jdunck, sorry for all the trouble from this PR

**Comment by ryanhiebert** [comment]
@endeepak Not at all. If I were designing a csv module myself, it probably would keep the keys ordered; it's a good feature. The main reason that I want to revert it is just so that we maintain as much consistency as possible with the builtin csv modules.

**Comment by jdunck** [comment]
That's a bit frustrating.  I think when the PR came in originally, I looked at the underlying implementation and saw it not ordered, but forgot to reply/close the PR.  Then yesterday I was trying to sweep up low-hanging PRs with fairly limited time/attention, and screwed up here.

Sorry about that. :-(

Ryan, I do want to land your branch and appreciate you merging up to make it easier.  I'll revert c0b7655248c4249e0c8 in a moment.
