### ISSUE TITLE
Allow headers to differ from fieldnames

### ISSUE THREAD

**Issue by svisser** [jdunck/python-unicodecsv#43]
In `DictWriter` the header is currently defined as:

```python
header = dict(zip(self.fieldnames, self.fieldnames))
```

This means the keys in the rows have to match the headers of the file. But that's inconvenient because the keys are often things like `dateOfOrder` whereas we'd like a human-readable header in the CSV file: "Date of order".

**Comment by tsroten** [comment]
@svisser unicodecsv mimics Python 2's csv module in that regard. unicodecsv is, after all, "a drop-in replacement for Python 2's csv module which supports unicode strings without a hassle."

You can write a header row manually by using the "[the underlying `writer` instance](https://docs.python.org/2/library/csv.html#csv.DictWriter)" (Python 2.7 docs), which in unicodecsv's instance would be [the underlying `UnicodeWriter` instance](https://github.com/jdunck/python-unicodecsv/blob/master/unicodecsv/__init__.py#L149). To expand on the example from the ``csv.DictWriter`` docs using unicodecsv:

```python
import unicodecsv as csv

with open('names.csv', 'w') as csvfile:
    fieldnames = ['first_name', 'last_name']
    dwriter = csv.DictWriter(csvfile, fieldnames=fieldnames)

    # Look closely at the next line.
    # We use the DictWriter instance's underlying ``UnicodeWriter`` instance.
    dwriter.writer.writerow(['First Name', 'Last Name'])

    dwriter.writerow({'first_name': 'Baked', 'last_name': 'Beans'})
    dwriter.writerow({'first_name': 'Lovely', 'last_name': 'Spam'})
    dwriter.writerow({'first_name': 'Wonderful', 'last_name': 'Spam'})
```

**Comment by svisser** [comment]
That makes sense, so we can't really add a parameter to `writeheader()` (although as a keyword argument with a default value it could work).

That being said, it does seem `writeheader()` creates a local variable but then doesn't use it?

```python
def writeheader(self):
    fieldnames = _stringify_list(self.fieldnames, self.encoding, self.encoding_errors)
    header = dict(zip(self.fieldnames, self.fieldnames))
    self.writerow(header)
```

**Comment by jdunck** [comment]
Hey folks, thanks for chiming in on these PRs. :)

I agree w @tsroten's suggestion and yeah @svisser that use of self.fieldnames rather than fieldnames is a mistake.

**Comment by svisser** [comment]
@jdunck thanks for your comments, I'll close this issue and make the necessary changes in my own code.
