### ISSUE TITLE
Need a new release that fixes issue where writer.writerow() returns the row

### ISSUE THREAD

**Issue by robvdl** [jdunck/python-unicodecsv#45]
This seems to have been fixed after the 0.9.4 release, I need this for streaming CSV's from Django using this example:

https://docs.djangoproject.com/en/1.7/howto/outputting-csv/

Because in the 0.9.4 release writer.writerow() still returns None, this just generates a CSV containing "NoneNoneNoneNone"... etc.

Can we please have an 0.9.5 release with this fix in it?

**Comment by mic159** [comment]
Yeah, can we please have a new release?

**Comment by jdunck** [comment]
I've just released 0.11.0
