### ISSUE TITLE
unicodecsv reads some cells as empty despite the fact they have values.

### ISSUE THREAD

**Issue by dchaplinsky** [jdunck/python-unicodecsv#48]
I'm having problems reading pretty simple CSV file, that I've exported from google spreadsheet:
https://gist.github.com/dchaplinsky/9791d15fb1b66b429044

This fields returned as "" (see https://gist.github.com/dchaplinsky/fb4533e7b27b456aabce).

I've tried to debug it last night, but had no success.
![monosnap 2015-03-11 13-42-13](https://cloud.githubusercontent.com/assets/131186/6595597/7438f16e-c7f4-11e4-8188-7f35e1905f7c.png)

**Comment by dchaplinsky** [comment]
I've also found that native CSV DictReader has the very same problem, while reader doesn't.

**Comment by dchaplinsky** [comment]
I'm an idiot, please ignore me.

**Comment by jdunck** [comment]
I doubt that's true -- if there was something confusing about using it, could you clarify how you were misled?  Perhaps a runtime warning or better docs are in order?

**Comment by dchaplinsky** [comment]
CSV that I was trying to use had two columns with identical names. Second one was always empty.

**Comment by jdunck** [comment]
OK, I just made #50 to make this less difficult to avoid in the future.
