### ISSUE TITLE
No isinstance unicode in Python3

### ISSUE THREAD

**Issue by DenisCarriere** [jdunck/python-unicodecsv#51]
The isinstance statement with unicode does not exist in python3:

```python
    if isinstance(s, unicode):
```
Here's how I fixed it in my versions, but I still don't know if it's actually the best way to test unicode so I won't do a pull request unless someone can tell me it's actually correct.

```python
# Example ONLY
if sys.version_info.major == 2:
    if isinstance(value, (str, unicode)):  # noqa
        return value

elif sys.version_info.major == 3:
    if isinstance(value, str):
        return value
```

## Python3 error

Traceback (most recent call last):
  File "/home/denis/Github/ACAPS-tools/parser.py", line 166, in <module>
    export('Guinea_Locations_Export.csv', ['google', 'bing', 'osm'])
  File "/home/denis/Github/ACAPS-tools/parser.py", line 124, in export
    writer.writeheader()
  File "/usr/local/lib/python3.4/dist-packages/unicodecsv/__init__.py", line 158, in writeheader
    self.writerow(header)
  File "/usr/lib/python3.4/csv.py", line 153, in writerow
    return self.writer.writerow(self._dict_to_list(rowdict))
  File "/usr/local/lib/python3.4/dist-packages/unicodecsv/__init__.py", line 86, in writerow
    return self.writer.writerow(_stringify_list(row, self.encoding, self.encoding_errors))
  File "/usr/local/lib/python3.4/dist-packages/unicodecsv/__init__.py", line 51, in _stringify_list
    return [_stringify(s, encoding, errors) for s in iter(l)]
  File "/usr/local/lib/python3.4/dist-packages/unicodecsv/__init__.py", line 51, in <listcomp>
    return [_stringify(s, encoding, errors) for s in iter(l)]
  File "/usr/local/lib/python3.4/dist-packages/unicodecsv/__init__.py", line 41, in _stringify
    if isinstance(s, unicode):
NameError: name 'unicode' is not defined

**Comment by tsroten** [comment]
It might be cleaner to keep that conditional statement as is. At the top of the module you could do this:
```python
is_python3 = sys.version_info.major == 3
if is_python3:
    unicode = str
```

Then, all references to `unicode` will work properly.

**Comment by DenisCarriere** [comment]
@tsroten Oh sweet, I've never thought of that! that looks good!

Thanks, I know that unicodecsv isn't really testing for Python3, but I'll incorporate in my code :+1:

**Comment by jackmaney** [comment]
This is probably a bit of a newb question, especially since I'm just making the transition from Python 2 to 3, but doesn't Python 3's `csv` handle unicode?

**Comment by DenisCarriere** [comment]
Python 3 does handle Unicode in the CSV module, however when you build your
code to work for both versions you will eventually have your code break at
the `isinstance` function since the `unicode` variable doesn't exist in
Python 3. This little code piece helps solve this issue.

**Comment by jdunck** [comment]
I've added py3 in 0.12.0 - please try it out and open another issue if you find specific problems. :)

**Comment by fletchowns** [comment]
@jdunck Thank you! It seems to work great for me. The only thing I noticed was that the setup.py has not been updated to indicate that this package works with Python 3. Created #55 for that.
