### ISSUE TITLE
Unbreak Python 2.6 after version 0.13.0?

### ISSUE THREAD

**Issue by xZise** [jdunck/python-unicodecsv#62]
pywikibot-core is currently using unicodecsv on Python 2.7 and 2.6 and removing support for Python 2.6 broke support. Now it's not that much of a problem as users could install an older version. But I wanted to ask whether you are interested in supporting 2.6 again by using `OrderedDict` from a third party library like `ordereddict` or `future`. If you want I could work on a pull request, but there still seem to be a lot of Python 2.6 users especially those using Redhat Linux.

Now if you are not interested you can just close this bug and we're going to limit the version to 0.13.0 on Python 2.6.

**Comment by ryanhiebert** [comment]
2.6 is supported again, via reverting that change that required `OrderedDict`.

**Comment by jdunck** [comment]
@xZise is it reasonable to upgrade to 0.14.1?

**Comment by xZise** [comment]
I hope you didn't revert because of us ;) Anyway if only 0.14.0 does not support Python 2.6 we can forbid only 0.14.0 on it so that new users will install the most recent version. I've done that in xZise/pywikibot-core@fe12b566d0d2411d428c9637d16a85c0283ac906 and currently let it run our tests on https://travis-ci.org/xZise/pywikibot-core/builds/81838549

It's not merged into the repository yet as I'm waiting for the results of these tests. Not sure what you mean with upgrade to 0.14.1 (if you mean something else) as we can't bring the users to install a the most recent version unless they install it with my new definition of course.

**Comment by ryanhiebert** [comment]
@xZise: Since 0.14.0 breaks your software, you'll need to note that it isn't compatible. It sounds like that's you're method. Are you satisfied to close this issue, then?

**Comment by xZise** [comment]
Okay 0.14.1 is now installed so it should be fine. Users who have 0.14.0 installed on Python 2.6 will get an error when they try to insta Pywikibot. I think that enough (apart from the fact that the user installed an invalid version beforehand).
