### ISSUE TITLE
Remove 2.6 from the classifiers

### ISSUE THREAD

**Issue by xZise** [jdunck/python-unicodecsv#63]
Just a minor note, but as you don't support 2.6 anymore it would be nice if you could remove it from the classifiers from `setup.py`. Otherwise the pypi page gives the impression you are still supporting it.

**Comment by ryanhiebert** [comment]
Python 2.6 is supported again, so we don't need to remove the classifier.

**Comment by xZise** [comment]
Then please update the README which explicitly lists the 2nd digit and add 2.6 to make it official ;)
